-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建存储桶
INSERT INTO storage.buckets (id, name, public)
VALUES 
 ('audio', 'audio', true),
 ('photos', 'photos', true),
 ('pdfs', 'pdfs', true);

-- 存储桶 RLS 策略
CREATE POLICY anon_select_audio ON storage.objects
FOR SELECT USING (bucket_id = 'audio');

CREATE POLICY users_insert_audio ON storage.objects
FOR INSERT WITH CHECK (
 bucket_id = 'audio' AND
 auth.role() = 'authenticated'
);

CREATE POLICY anon_select_photos ON storage.objects
FOR SELECT USING (bucket_id = 'photos');

CREATE POLICY users_insert_photos ON storage.objects
FOR INSERT WITH CHECK (
 bucket_id = 'photos' AND
 auth.role() = 'authenticated'
);

CREATE POLICY anon_select_pdfs ON storage.objects
FOR SELECT USING (bucket_id = 'pdfs');

CREATE POLICY users_insert_pdfs ON storage.objects
FOR INSERT WITH CHECK (
 bucket_id = 'pdfs' AND
 auth.role() = 'authenticated'
);

