-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建故事/回答表
CREATE TABLE public.stories (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 question_id INTEGER NOT NULL,
 chapter TEXT NOT NULL,
 question_text TEXT NOT NULL,
 raw_text TEXT,
 polished_text TEXT,
 audio_url TEXT,
 photos TEXT[],
 followups JSONB,
 is_completed BOOLEAN DEFAULT FALSE,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.stories ENABLE ROW LEVEL SECURITY;

-- 用户只能查看和操作自己的故事
CREATE POLICY users_select_own_stories ON public.stories
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY users_insert_own_stories ON public.stories
FOR INSERT WITH CHECK (user_id = auth.uid());

CREATE POLICY users_update_own_stories ON public.stories
FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

CREATE POLICY users_delete_own_stories ON public.stories
FOR DELETE USING (user_id = auth.uid());

