-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS sms_codes (
 id SERIAL PRIMARY KEY,
 phone TEXT NOT NULL,
 code TEXT NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 used BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建索引
CREATE INDEX idx_sms_codes_phone ON sms_codes(phone);
CREATE INDEX idx_sms_codes_created_at ON sms_codes(created_at);

-- 添加RLS策略
ALTER TABLE sms_codes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_insert_sms_codes ON sms_codes
 FOR INSERT
 WITH CHECK (true);

CREATE POLICY anon_select_sms_codes ON sms_codes
 FOR SELECT
 USING (true);

