-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建订单表
CREATE TABLE public.orders (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
 order_no TEXT UNIQUE NOT NULL,
 plan_type TEXT NOT NULL,
 plan_name TEXT NOT NULL,
 price INTEGER NOT NULL,
 status TEXT DEFAULT 'pending',
 paid_at TIMESTAMPTZ,
 transaction_id TEXT,
 pdf_url TEXT,
 book_shipped BOOLEAN DEFAULT FALSE,
 book_tracking_no TEXT,
 created_at TIMESTAMPTZ DEFAULT NOW(),
 updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 用户只能查看自己的订单
CREATE POLICY users_select_own_orders ON public.orders
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY users_insert_own_orders ON public.orders
FOR INSERT WITH CHECK (user_id = auth.uid());

