-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


-- 创建用户注册时自动创建配置文件的触发器
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
 INSERT INTO public.profiles (id, username, phone, avatar_url)
 VALUES (
 NEW.id,
 NEW.raw_user_meta_data ->> 'username',
 NEW.raw_user_meta_data ->> 'phone',
 NEW.raw_user_meta_data ->> 'avatar_url'
 );
 RETURN NEW;
END;
$$;

-- 创建触发器
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
 AFTER INSERT ON auth.users
 FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

